variable "environment" {
  description = "Environment name: dev | staging | prod"
  type        = string
  default     = "prod"
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "image_tag" {
  description = "Docker image tag for api-core (ECS)"
  type        = string
  default     = "latest"
}

variable "lambda_fiscal_image_tag" {
  description = "Docker image tag for lambda-fiscal (ECR)"
  type        = string
  default     = "latest"
}

# ── Cost knobs ─────────────────────────────────────────────────────────────────
# dev:  db.t3.micro (1 vCPU, 1 GB) — ~$12/month single-AZ
# prod: db.t3.small (2 vCPU, 2 GB) — ~$25/month single-AZ
variable "db_instance_class" {
  type    = string
  default = "db.t3.micro"
}

# dev:  1 task (zero HA, minimum cost)
# prod: 2 tasks minimum for high availability
variable "api_desired_count" {
  type    = number
  default = 1
}

# ECS task size — Fargate minimum: 256 CPU / 512 MB ≈ $9/month
variable "api_cpu" {
  type    = number
  default = 256
}

variable "api_memory" {
  type    = number
  default = 512
}

# Multi-AZ doubles RDS cost. Default false — re-enable only when SLA requires < 1 min RTO.
variable "rds_multi_az" {
  description = "Enable Multi-AZ standby for RDS (doubles compute cost)."
  type        = bool
  default     = false
}

# ── Secrets ───────────────────────────────────────────────────────────────────
# db_password is no longer a variable — generated by random_password.db_master
# in secrets.tf and stored in the encrypted S3 Terraform state.

variable "jwt_secret" {
  description = "JWT signing secret for the auth service"
  type        = string
  sensitive   = true
  default     = "change-me-jwt-secret"
}

variable "focus_nfe_token" {
  description = "Focus NF-e API token (https://focusnfe.com.br — account → API token)"
  type        = string
  sensitive   = true
  default     = "change-me-focus-token"
}

variable "lambda_notifications_image_tag" {
  description = "Docker image tag for lambda-notifications (ECR)"
  type        = string
  default     = "latest"
}

variable "ses_from_email" {
  description = "Verified SES sender address used as the From email for all notifications"
  type        = string
  default     = "noreply@example.com"
}

variable "ses_from_name" {
  description = "Display name shown alongside the From email address"
  type        = string
  default     = "Orquestra ERP"
}

variable "lambda_billing_image_tag" {
  description = "Docker image tag for lambda-billing (ECR)"
  type        = string
  default     = "latest"
}

variable "itau_client_id" {
  description = "Itaú Empresas API client_id for boleto generation (OAuth2 client_credentials)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "itau_client_secret" {
  description = "Itaú Empresas API client_secret for boleto generation (OAuth2 client_credentials)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "app_public_origins" {
  description = <<-EOT
    Origens (scheme+host) autorizadas a fazer upload direto no bucket de fotos
    de visita técnica via presigned POST (CORS). Inclui localhost para
    desenvolvimento local contra LocalStack.
  EOT
  type        = list(string)
  default     = ["https://orquestraerp.com.br", "https://www.orquestraerp.com.br", "http://localhost:5173"]
}

variable "acm_certificate_arn" {
  description = <<-EOT
    ARN of the ACM certificate for orquestraerp.com.br (must be in us-east-1).
    Leave empty ("") on the first deploy — CloudFront will use its default certificate.
    Steps to activate the custom domain:
      1. Run terraform apply (first deploy) to create the Route 53 hosted zone.
      2. terraform output route53_nameservers  →  copy the 4 NS values.
      3. Update the domain registrar nameservers to the Route 53 values.
      4. Wait 5–30 min for ACM to auto-validate via DNS and issue the certificate.
      5. Copy the certificate ARN from ACM console → set TF_VAR_ACM_CERTIFICATE_ARN
         in GitHub Secrets → re-run the deploy workflow.
  EOT
  type        = string
  default     = ""
}
