-- Add fiscal/tax fields to invoices and invoice_items for NF-e emission.
-- ICMS, PIS, COFINS are "por dentro" (embedded in the sale price — informational).
-- IPI is "por fora" (added on top — affects the total).

ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS tax_regime   VARCHAR(30)   NOT NULL DEFAULT 'lucro_presumido',
  ADD COLUMN IF NOT EXISTS origin_state CHAR(2)       NOT NULL DEFAULT 'SP',
  ADD COLUMN IF NOT EXISTS icms_total   DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis_total    DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins_total DECIMAL(15,2) NOT NULL DEFAULT 0;

ALTER TABLE invoice_items
  ADD COLUMN IF NOT EXISTS icms_cst     VARCHAR(3),
  ADD COLUMN IF NOT EXISTS icms_base    DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_rate    DECIMAL(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_value   DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis_cst      VARCHAR(2),
  ADD COLUMN IF NOT EXISTS pis_base     DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis_rate     DECIMAL(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis_value    DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins_cst   VARCHAR(2),
  ADD COLUMN IF NOT EXISTS cofins_base  DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins_rate  DECIMAL(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins_value DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi_rate     DECIMAL(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi_value    DECIMAL(15,2) NOT NULL DEFAULT 0;
